name: Generate MD Files

on:
  push:
    branches:
      - "main"

jobs:
  generate-md:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"

      - name: Run Go script
        run: |
          go run internal/main.go

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          #     # 변경 사항 확인
          # if git diff --quiet; then
          #   echo "No changes to commit"
          # else
          git add .
          git commit -m 'update md'
          git push origin ${{ github.head_ref }}
          echo "Changes committed and pushed"
          # fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
